---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-6.5
    driver:
      customize:
        memory: 512
      network:
        - ["forwarded_port", {guest: 8080, host: 6581}]
  - name: ubuntu-12.04
    driver:
      customize:
        memory: 384
      network:
        - ["forwarded_port", {guest: 8080, host: 1281}]
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 384
      network:
        - ["forwarded_port", {guest: 8080, host: 1481}]
  - name: debian-7.7
    driver:
      customize:
        memory: 384
      network:
        - ["forwarded_port", {guest: 8080, host: 7781}]
  - name: centos-7.0
    driver:
      customize:
        memory: 512
      network:
        - ["forwarded_port", {guest: 8080, host: 7081}]
  - name: debian-6.0.10
    driver:
      customize:
        memory: 384
      network:
        - ["forwarded_port", {guest: 8080, host: 6081}]


suites:
  - name: default
    run_list:
      - recipe[tonicdns::default]
    attributes:
  - name: test
    run_list:
      - recipe[tonicdns::test]
    attributes: