---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04-i386
  - name: centos-6.5-i386
  - name: ubuntu-14.04-i386
  - name: debian-7.6-i386

suites:
  - name: default
    run_list:
      - recipe[tonicdns::default]
    attributes:
  - name: test
    run_list:
      - recipe[tonicdns::test]
    attributes: